### ISSUE TITLE
刷新加载慢

### ISSUE THREAD

**Issue by xiaoxuez** [TrumanDu/kibana-plugin-development-tutorial#1]
你好，最近正在开发kibana插件，这个tutorial真是太给力了。但感到比较乏力的是，开发的过程中，修改代码使之生效需要刷新，但kibana刷新实在是太慢..有什么建议吗？谢谢

**Comment by TrumanDu** [comment]
@xiaoxuez 如果有用的话，方便的话，给个star.你说的刷新慢是开发模式，还是kibana 功能刷新慢呢？

**Comment by xiaoxuez** [comment]
emmm...   我应该是个新手。对于您说的开发模式，还是功能刷新有点不太分得清楚。具体表现就是在开发的时候，我修改过代码，需要刷新浏览器才能看到修改的效果，但刷新浏览器的话，就会出现kibana加载的界面，就是Loading Kibana..有时候这个界面需要等十好几秒。这样的话开发体验不太好

**Comment by TrumanDu** [comment]
@xiaoxuez 是的，这个也区分你改得是前端代码，还是server代码，server代码刷新确实时间有点久，前端代码修改没那么久，基本上久是把缓存清掉就好了。我这边只有重启kibana服务才会耗时几十秒，如果前端代码刷新还是很慢的话，建议你可以chrome里面修改代码，但别刷新页面。希望能帮到你
